# Trust policy: generated from the real external_id returned by the storage credential
data "databricks_aws_unity_catalog_assume_role_policy" "this" {
  provider       = databricks.workspace
  aws_account_id = data.aws_caller_identity.current.account_id
  role_name      = "${var.prefix}-catalog-storage"
  external_id    = databricks_storage_credential.this.aws_iam_role[0].external_id
}

resource "aws_iam_role" "catalog_storage" {
  name               = "${var.prefix}-catalog-storage"
  assume_role_policy = data.databricks_aws_unity_catalog_assume_role_policy.this.json
}

# S3 access policy: generated by the provider so it stays in sync with Databricks requirements
# (the provider docs note this data source has an evolving API)
data "databricks_aws_unity_catalog_policy" "this" {
  provider       = databricks.workspace
  aws_account_id = data.aws_caller_identity.current.account_id
  bucket_name    = aws_s3_bucket.catalog.id
  role_name      = "${var.prefix}-catalog-storage"
}

resource "aws_iam_policy" "catalog_storage" {
  name   = "${var.prefix}-catalog-storage-policy"
  policy = data.databricks_aws_unity_catalog_policy.this.json
}

resource "aws_iam_role_policy_attachment" "catalog_storage" {
  role       = aws_iam_role.catalog_storage.name
  policy_arn = aws_iam_policy.catalog_storage.arn
}

resource "time_sleep" "wait_for_iam_propagation" {
  depends_on      = [aws_iam_role_policy_attachment.catalog_storage]
  create_duration = "30s"
}
